### ISSUE TITLE
FF 36.0.1: icon is missing from toolbar

### ISSUE THREAD

**Issue by angry-master-yoda** [olsh/Feedly-Notifier-Firefox#116]
After Firefox update (36.0.1) Feedly Notifier icon is missing from toolbar. How can I restore it?

**Comment by olsh** [comment]
You can restore the icon using the "customize button".
https://www.mozilla.org/en-US/firefox/desktop/customize/

**Comment by angry-master-yoda** [comment]
**Upd.:** It's missing from "Additional Tools and Features" too.

**Comment by olsh** [comment]
Have you tried to reinstall the addon?

**Comment by angry-master-yoda** [comment]
Yes. No effect.

**Comment by olsh** [comment]
Try to create [a new FF profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles#w_creating-a-profile).

**Comment by angry-master-yoda** [comment]
Хмм... По-моему, это как-то неправильно.

**Comment by olsh** [comment]
Только лишь для теста.

**Comment by angry-master-yoda** [comment]
Что ж...
Новый профиль (ни синхронизации ни аддонов) -> добавить Feedly Notifier -> удобно расположить иконку.
Всё замечательно.

Иконка пропала после обновления до 36.0.1 (на windows). на CentOS (31.x.x) всё видно, всё замечательно.
Такая фигня, кстати, со многими дополнениями случалась.

**Comment by olsh** [comment]
Ну тогда у меня есть подозрения что это несовместимость с каким-то из аддонов.
Например были такие проблемы с CustomizableUI
https://github.com/olsh/Feedly-Notifier-Firefox/issues/97

Или что-то поломали в API в этой версии, так же я использую sic(!)[рекомендуемый нестабильный API](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_toggle) для иконки, может проблема в этом.

Не знаю что предложить.
Попробуйте поотключать аддоны, может быть найдется виновный.

**Comment by angry-master-yoda** [comment]
Я пока что плагинов не писал - руки не дошли :-).

Ну как же так-то? Под 36.0.0 все дружили, а под 36.0.1 перестали. Обидно. Причём не видно только иконку - уведомления о новых фидах приходят исправно.

**Comment by angry-master-yoda** [comment]
Вы не поверите...

Поигрался с чистым профилем, закрыл всё это, вернулся к старому. А иконка-то - вот она! Появилась. Обновлений не было. В чём дело, не понял :-).

Да, мы офигели. Надо дома ещё такую же штуку проделать.

**Comment by olsh** [comment]
Проблемы больше нет? Закрываем?

**Comment by angry-master-yoda** [comment]
Ой...
Прошу прощения, что не писал - у меня тут пререлиз весьма мучительно выходит, вообще обо всём забыл.

Нет, дома проблема осталась. Всё как было - уведомления приходят, иконки на тулбаре нет.
Может кеши какие почистить надо?

**Comment by olsh** [comment]
Вы можете открыть консоль (ctrl + shift + j) и посмотреть есть ли там ошибки, после старта браузера?
Эта проблема возникает не только у вас, но я у себя никак не могу ее воспроизвести.
Скажите еще, какие аддоны у вас установлены?

**Comment by angry-master-yoda** [comment]
Что-то там много всего... Просто таки затрудняюсь выбрать что-то конкретное.
А вообще, подобная ошибка где-то как-то уже была. Но потом расширение обновилось, и она исчезла.
Кэши (кажется, все возможные) очищать пробовал - эффекта не было.
Расширений у меня много. Что конкретно интерсует?

А это консоль:
ReferenceError: reference to undefined property e[x.status] frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:81:27976
Object { , 5 more… } runner.js:164
Object { , 5 more… } Promise-backend.js:873
"DEPRECATED: The widget module is deprecated.  Please consider using the sdk/ui module instead.
Traceback (most recent call last):
  File "resource://gre/modules/services-sync/service.js", line 1260, in sync/<
    return this._lockedSync.apply(this, arguments);
  File "resource://gre/modules/services-sync/service.js", line 1268, in _lockedSync
    return this._lock("service.js: sync",
  File "resource://services-sync/util.js", line 103, in WrappedLock
    return func.call(thisArg);
  File "resource://services-sync/util.js", line 148, in WrappedNotify
    let ret = func.call(thisArg);
  File "resource://gre/modules/services-sync/service.js", line 1278, in onNotify
    synchronizer.sync();
  File "resource://services-sync/stages/enginesync.js", line 149, in sync
    if (!(this._syncEngine(engine)) || this.service.status.enforceBackoff) {
  File "resource://services-sync/stages/enginesync.js", line 199, in _syncEngine
    engine.sync();
  File "resource://services-sync/engines.js", line 663, in Engine.prototype.sync
    this._notify("sync", this.name, this._sync)();
  File "resource://services-sync/util.js", line 148, in WrappedNotify
    let ret = func.call(thisArg);
  File "resource://services-sync/engines.js", line 1505, in SyncEngine.prototype._sync
    this._uploadOutgoing();
  File "resource://services-sync/engines.js", line 1449, in SyncEngine.prototype._uploadOutgoing
    this._store._sleep(0);
  File "resource://services-sync/engines.js", line 282, in _sleep
    Async.waitForSyncCallback(cb);
  File "resource://services-common/async.js", line 102, in waitForSyncCallback
    thread.processNextEvent(true);
  File "resource://gre/modules/Promise-backend.js", line 691, in this.PromiseWalker.scheduleWalkerLoop/<
    DOMPromise.resolve().then(() => this.walkerLoop());
  File "resource://gre/modules/Promise-backend.js", line 749, in this.PromiseWalker.walkerLoop
    this.handlers.shift().process();
  File "resource://gre/modules/Promise-backend.js", line 870, in Handler.prototype.process
    nextValue = this.onResolve.call(undefined, nextValue);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 86, in startup/</<
    run(options);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 145, in run
    let program = main(options.loader, options.main);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 684, in main
    return loader.load(loader, module).exports;
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 129, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 318, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 267, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://jid0-w1uvmold6vgudaierurjcpqx1dq-at-jetpack/firetube/lib/main.js", line 1, in null
    const widgets = require("sdk/widget");
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 591, in require
    freeze(load(loader, module));
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 129, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 318, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 267, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://gre/modules/commonjs/sdk/widget.js", line 59, in null
    require("./util/deprecate").deprecateUsage(
  File "resource://gre/modules/commonjs/sdk/util/deprecate.js", line 18, in deprecateUsage
    let stack = get().slice(2);" deprecate.js:21
"[CustomizableUI]" "NotFoundError: Node was not found -- :1074" CustomizableUI.jsm:174
"The "fb-root" div has not been created, auto-creating" all.js:64:238
"The "fb-root" div has not been created, auto-creating" sdk.js:64:238
"1 tags failed to render in 30000 ms" sdk.js:64:238
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:80:221
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:80:3523
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:80:14574
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:81:29524
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:82:8006
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:82:8707
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:82:9663
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:82:10701
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:82:10945
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:83:5122
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:83:6527
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:111:3690
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:111:9487
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:111:11272
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:111:11353
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:175:24710
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:175:28657
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:175:30673
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:175:30917
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:175:31060
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:175:31274
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:175:31443
SyntaxError: test for equality (==) mistyped as assignment (=)? frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:175:32586
ReferenceError: reference to undefined property n.mark frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:9:2385
ReferenceError: reference to undefined property C[e.toLowerCase(...)] frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:34:2359
ReferenceError: reference to undefined property e.nodeType frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:80:25661
ReferenceError: reference to undefined property o.selector frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:80:29933
ReferenceError: reference to undefined property s.extends frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:34:683
ReferenceError: reference to undefined property this.find(...).filter(...)[0] frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:175:17917
ReferenceError: reference to undefined property n[t] frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:80:26178
ReferenceError: reference to undefined property b.relatedTarget rs=AGLTcCN3EhqZB7q8IyxKaOrd0rQb5ScN9g:216:98
TypeError: document.getElementById(...) is null overlay.js:7333:4
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:6384
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:6593
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:6603
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:7885
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:9875
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:11305
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:11901
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:11939
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:12900
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:13212
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:15009
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:15273
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:15421
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:16469
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:18800
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:18889
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:18949
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:20226
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:20786
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:2:20894
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:3:19754
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:3:19881
SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function jquery-1.11.1.min.js:3:26151
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:4:1899
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:4:4361
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:4:10436
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:4:13631
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:4:14075
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:4:14489
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:4:16778
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:4:19271
SyntaxError: test for equality (==) mistyped as assignment (=)? jquery-1.11.1.min.js:4:21164
ReferenceError: reference to undefined property Z.event.triggered frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:80:31679
ReferenceError: reference to undefined property m.event.triggered jquery-1.11.1.min.js:3:6772
ReferenceError: reference to undefined property m.cache[a[m.expando]] jquery-1.11.1.min.js:3:937
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:34:1559
lpmanuallogins.length is 0
TypeError: document.getElementById(...) is null overlay.js:7333:4
ReferenceError: reference to undefined property Z.event.triggered frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:80:30048
ReferenceError: deprecated caller usage rs=AGLTcCN3EhqZB7q8IyxKaOrd0rQb5ScN9g:263:810
ReferenceError: deprecated caller usage rs=AGLTcCN3EhqZB7q8IyxKaOrd0rQb5ScN9g:264:0
ReferenceError: reference to undefined property this.L rs=AGLTcCN3EhqZB7q8IyxKaOrd0rQb5ScN9g:2471:337
ReferenceError: reference to undefined property this.yg rs=AGLTcCN3EhqZB7q8IyxKaOrd0rQb5ScN9g:1027:322
ReferenceError: reference to undefined property this.Nd rs=AGLTcCN3EhqZB7q8IyxKaOrd0rQb5ScN9g:1254:509
ReferenceError: reference to undefined property this.$b rs=AGLTcCN3EhqZB7q8IyxKaOrd0rQb5ScN9g line 6 > eval:182:289
ReferenceError: reference to undefined property this.rb rs=AItRSTNGWVKlWLWhpmI-nW6qMTjdQZfK1Q:291:312
ReferenceError: reference to undefined property H.e 4085740263-lcs_client_bin.js:183:166
ReferenceError: reference to undefined property this.ea rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA:3461:85
ReferenceError: reference to undefined property this.xa rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA:552:627
ReferenceError: reference to undefined property this.ra rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA:1634:111
ReferenceError: reference to undefined property this.ea rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA:2462:35
ReferenceError: reference to undefined property this.ea rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA:3428:560
ReferenceError: reference to undefined property b.Oa rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA:2316:100
ReferenceError: reference to undefined property this.Ia rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA:542:432
ReferenceError: reference to undefined property this.Ra rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA line 24 > eval:104:512
ReferenceError: reference to undefined property this.Vb rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA:3383:451
ReferenceError: reference to undefined property this.$b rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA line 24 > eval:81:641
ReferenceError: reference to undefined property this.Vb rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA:3959:71
ReferenceError: reference to undefined property this.ea rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA:3937:498
ReferenceError: reference to undefined property this.Da rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA:1439:315
ReferenceError: reference to undefined property this.ea rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA line 24 > eval:185:617
ReferenceError: reference to undefined property this.kb rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA:1541:82
ReferenceError: reference to undefined property this.QK rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA line 24 > eval:20:585
ReferenceError: reference to undefined property this.ea rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA line 24 > eval:19:386
ReferenceError: reference to undefined property this.ha rs=AHGWq9DPPQhwijN3fFcchQyr_KRZCOL9kA line 24 > eval:11:48
ReferenceError: reference to undefined property this[c] jquery-1.11.1.min.js:2:24351
ReferenceError: reference to undefined property m.event.triggered jquery-1.11.1.min.js:3:5070
ReferenceError: reference to undefined property a.result jquery-1.11.1.min.js:3:8575
SyntaxError: test for equality (==) mistyped as assignment (=)? github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:32:19686
SyntaxError: test for equality (==) mistyped as assignment (=)? github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:32:20934
SyntaxError: test for equality (==) mistyped as assignment (=)? github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:36:3440
SyntaxError: test for equality (==) mistyped as assignment (=)? github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:36:8616
SyntaxError: test for equality (==) mistyped as assignment (=)? github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:36:12371
SyntaxError: test for equality (==) mistyped as assignment (=)? github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:49:20810
SyntaxError: test for equality (==) mistyped as assignment (=)? github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:50:17943
SyntaxError: test for equality (==) mistyped as assignment (=)? github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:50:20549
SyntaxError: test for equality (==) mistyped as assignment (=)? github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:51:24903
SyntaxError: test for equality (==) mistyped as assignment (=)? github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:52:17323
SyntaxError: test for equality (==) mistyped as assignment (=)? github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:52:29879
SyntaxError: test for equality (==) mistyped as assignment (=)? github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:55:6109
SyntaxError: test for equality (==) mistyped as assignment (=)? github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:55:19785
ReferenceError: assignment to undeclared variable DateInput github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:1:2263
ReferenceError: reference to undefined property O.GoogleAnalyticsObject github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:50:4051
ReferenceError: reference to undefined property Er.h[t] github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:50:18911
ReferenceError: reference to undefined property t[ki] github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:50:13033
ReferenceError: reference to undefined property this.w[(":" + t)] github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:49:32770
ReferenceError: reference to undefined property e[F.floor(...)] github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:49:32221
ReferenceError: reference to undefined property e.result frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:81:680
SyntaxError: test for equality (==) mistyped as assignment (=)? api.js:1:7195
Firefox can't establish a connection to the server at wss://live.github.com/_sockets/MjM4NDM4NzowZWQ4ODA5YTQwNDllY2JiZDQ3ZWNiZDNjZTAzZTkzNjo0ZGM3NjYzYzkyMTgwNTNhZTVlNzgxNDdkYjc0ODllN2MwYWM0NWU5ZDAxMmU1NWZmNGE2NTM4YjFkYjQxNjhl--1352926129c8c6b2acb35ec97055983042ba7789. github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:36:0
The connection to wss://live.github.com/_sockets/MjM4NDM4NzowZWQ4ODA5YTQwNDllY2JiZDQ3ZWNiZDNjZTAzZTkzNjo0ZGM3NjYzYzkyMTgwNTNhZTVlNzgxNDdkYjc0ODllN2MwYWM0NWU5ZDAxMmU1NWZmNGE2NTM4YjFkYjQxNjhl--1352926129c8c6b2acb35ec97055983042ba7789 was interrupted while the page was loading. github-3db81a421ebe0d913a89557241623ecef42b40a31f8425a3f46f09d84b0028a1.js:36:0
ReferenceError: assignment to undeclared variable kd inline02.js:365:7
ReferenceError: reference to undefined property $(...)[0] frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:175:31749
Key event not available on some keyboard layouts: key="i" modifiers="accel alt shift" browser.xul
Key event not available on some keyboard layouts: key="j" modifiers="accel alt" browser.xul
Key event not available on some keyboard layouts: key="f" modifiers="accel alt shift" browser.xul
Key event not available on some keyboard layouts: key="b" modifiers="accel alt shift" browser.xul
Key event not available on some keyboard layouts: key="b" modifiers="accel,alt" browser.xul
Key event not available on some keyboard layouts: key="h" modifiers="control alt" browser.xul
Key event not available on some keyboard layouts: key="n" modifiers="accel, alt" browser.xul
Key event not available on some keyboard layouts: key="t" modifiers="accel,alt" browser.xul
Key event not available on some keyboard layouts: key="x" modifiers="accel,alt" browser.xul
Key event not available on some keyboard layouts: key="t" modifiers="alt accel" browser.xul
Key event not available on some keyboard layouts: key="a" modifiers="alt control" browser.xul
Key event not available on some keyboard layouts: key="c" modifiers="control alt" browser.xul
Key event not available on some keyboard layouts: key="x" modifiers="control alt" browser.xul
Key event not available on some keyboard layouts: key="o" modifiers="control alt" browser.xul
Key event not available on some keyboard layouts: key="s" modifiers="control,alt" browser.xul
Key event not available on some keyboard layouts: key="c" modifiers="accel,alt" browser.xul
Key event not available on some keyboard layouts: key="v" modifiers="control alt" browser.xul
Importing XUL nodes into a content document is deprecated. This functionality may be removed soon. jquery-1.7.1.min.js:3:0
lpmanuallogins.length is 0
ReferenceError: reference to undefined property f.headers frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:81:29164
ReferenceError: reference to undefined property e.username frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:81:32387
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://assets-cdn.github.com https://collector-cdn.github.com"). 116:1:0
value is not a non-null object tabbrowser.xml:430:0
ReferenceError: reference to undefined property e[x.status] frameworks-2c8ae50712a47d2b83d740cb875d55cdbbb3fdbccf303951cc6b7e63731e0c38.js:81:27976
ReferenceError: reference to undefined property this._currentTool sidebar.js:184:0

**Comment by olsh** [comment]
Да конкретно у меня нет предположений, какое расширение может конфликтовать. Чаще всего это расширения которые кастомизируют внешний вид FF. Например такие https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/
Попробуйте поотключать по одному расширения.

Судя по логам, у вас как минимум 1 расширениe использует deprecated widget, что *теоретически* может быть источником ошибки.

**Comment by angry-master-yoda** [comment]
Даже не знаю, что сказать... Да, Classic Theme Restorer у меня установлен (без него как-то уныло). Но на работе с этим всё нормально, а дома - увы... Несмотря на то, что набор плагинов одинаковый (они нынче синхронизируются).
Я потому и спрашивал про кэш какой-нибудь.
Поотключать я, конечно, попробую, но как-то это неправильно.

**Comment by olsh** [comment]
> Я потому и спрашивал про кэш какой-нибудь.

Кэша, который как либо влиял на иконку, у аддона нет.

> Поотключать я, конечно, попробую, но как-то это неправильно.

Я не советую вам отключать аддоны и оставить только Feedly Notifier навсегда, надо лишь понять, что вызывает этот баг, после этого я буду искать решение.
Баг проявляется у <1% пользователей, никто пока толком не нашел проблему, у себя я его воспроизвести не могу, соответственно - я не знаю что исправлять.

**Comment by angry-master-yoda** [comment]
Да я понимаю... Просто аддонов много.

**Comment by angry-master-yoda** [comment]
Свежие сплетни... Сорри, внятно изложить не могу.
Случайно нажал на линк с попап-рекламой, взлетело новое окошко с (внезапно!) потерянной иконкой на тулбаре. Быстренько нажал на customize в новом окне и утащил её в общую кучу, а потом вытащил обратно на тулбар. Понятно рассказал, не?
Сейчас могу сказать, что:
1) _моя_ проблема решена;
2) другие плагины явно не при чём;
3) наверное сам тулбар виноват...

**Comment by olsh** [comment]
Спасибо за исследование. :+1: 

> 2) другие плагины явно не при чём;
3) наверное сам тулбар виноват...

Не показатель. Плагины могут изменять поведение тулбаров.
Понятно лишь то, что при открытии второго окна иконка появилась и пропадает в первом. Теперь осталось выяснить как воспроизвести.

**Comment by angry-master-yoda** [comment]
Не, не так (см. первое сообщение).
При обновлении иконка исчезла (явно что-то произошло с тулбаром, т.к. остальные иконки тоже расползлись по непонятным местам), а при открытии нового окна появилась _на новом тулбаре_.
А как воспроизвести обновление?

PS Да не за что.

**Comment by olsh** [comment]
> А как воспроизвести обновление?

Поставить из архива и обновить, например.
https://ftp.mozilla.org/pub/mozilla.org/firefox/releases/

**Comment by angry-master-yoda** [comment]
Ааа... Не подумал.

**Comment by olsh** [comment]
Удалось идентифицировать источник проблемы?

**Comment by angry-master-yoda** [comment]
Неа.
Более того, с тех пор, похоже, ещё обновление прошло, и тулбар стал вести себя очень хорошо.
А проблема, похоже, именно в кешировании чего-то где-то.  Причём кеш не глобальный, а где-то на уровне текущего окна.
Что, у остальных проблема осталась?

**Comment by olsh** [comment]
А какая версия плагина стоит? 2.10.5? Я недавно новую версию выкладывал.

**Comment by angry-master-yoda** [comment]
Не знаю :-).
Оно ведь фоном обновляется.

**Comment by angry-master-yoda** [comment]
Дома посмотрю (постараюсь не забыть).

**Comment by angry-master-yoda** [comment]
Firefox 38.0.5, Feedly Notifier 2.10.5.
